name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Run tests (Pytest)
      run: |
        # Adiciona o diretório atual ao PYTHONPATH para encontrar o módulo 'app'
        export PYTHONPATH=$PWD
        pytest
    
    # Adicionando a validação de segurança Gitleaks, conforme solicitado
    - name: Run Gitleaks (Security Scan)
      uses: zricethezav/gitleaks-action@v2
      # Nota: Este passo pode falhar devido à necessidade de uma chave de licença (GITLEAKS_LICENSE)
      # se o seu ambiente for uma organização (como o Senac/GitHub Classroom).
      # Mantenha-o, mas se falhar, entre em contato com seu instrutor.
