name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Run tests (Pytest)
      run: |
        # Adiciona o diretório atual ao PYTHONPATH para encontrar o módulo 'app'
        export PYTHONPATH=$PWD
        pytest

        #Este passo é para o Gitleaks, se ele não for incluído automaticamente pelo Classroom.
        - name: Run Gitleaks
          uses: zricethezav/gitleaks-action@v2
          with:
          config: .gitleaks.toml # (Ou um arquivo de configuração específico se existir)
